spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    database: mysql
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/courseappdb_users?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"


server:
  port: 8901
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

signing:
  key: 345345fsdgsf5345
