spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    database: mysql
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/courseappdb_courses?createDatabaseIfNotExist=true"
    username: "root"
    password: "{cipher}5d4e0cfcd9fbbc4b4ba5f053c25eb452389f556ddb9d46979e4a434aa116933d"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.courseapp: DEBUG
